### ISSUE TITLE
Error reading file- xpt (_init, and _read_header)

### ISSUE THREAD

**Issue by sbjain** [selik/xport#21]
Code used below- simple open and read all rows from xpt file

import xport
#this portion is for opening and closing xpt files
with open('bg.xpt', 'rb') as f:
    for row in xport.Reader(f):
        print row

Error:
Traceback (most recent call last):
  File "test1.py", line 18, in <module>
    for row in xport.Reader(f):
  File "/usr/lib/python2.7/site-packages/xport.py", line 160, in __init__
    version, os, created, modified = self._read_header()
  File "/usr/lib/python2.7/site-packages/xport.py", line 197, in _read_header
    tokens = tuple(t.rstrip() for t in struct.unpack(fmt, raw))
struct.error: unpack requires a string argument of length 80

**Comment by sbjain** [comment]
Please ignore this error. 

Found the issue, the file gets empty after converting from xpt to csv format. -- since file is empty, there was error in that no string length present.

Thanks.
